# Generated by Django 5.2.4 on 2025-08-27 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='location_lat',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='location_lon',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='road',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='speed',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='type',
            field=models.CharField(default='bus', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='road',
            name='length_km',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='road',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('accident', 'Accident'), ('congestion', 'Congestion'), ('road_work', 'Road Work'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('location_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location_long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='traffic.road')),
            ],
        ),
        migrations.CreateModel(
            name='TrafficData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed_kph', models.DecimalField(decimal_places=2, max_digits=6)),
                ('position_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('position_long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_data', to='traffic.road')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_data', to='traffic.vehicle')),
            ],
        ),
    ]
